model: 'molnet'
dataset: 'chirality'

paths: 
  train_data: './data/ChirBase_eo/exp/od_sr_clean_train.pkl' 
  valid_data: './data/ChirBase_eo/exp/od_sr_clean_test.pkl'

model_para: 
  in_channels: 22
  num_atoms: 200
  encoder_layers: [64, 64, 128, 256, 512]
  emb_dim: 1024
  k: 5
  decoder_layers: [512, 256, 128, 64]
  dropout: 0.3
  out_channels: 1

train_para: 
  batch_size: 32
  epochs: 500
  lr: 0.00001
  num_workers: 0
  weight_decay: 0.9
  scheduler: 
    milestones: [10, 20, 40]
    gamma: 0.5
    
