model: 'molnet'
dataset: 'chirality'

paths: 
  train_data: './data/Chirality/chirbase_clean_train.sdf'
  valid_data: './data/Chirality/chirbase_clean_test.sdf'
  all_data: './data/Chirality/chirbase_clean.sdf'

model_para: 
  in_channels: 21
  num_atoms: 300
  num_add: 0
  encoder_layers: [64, 64, 128, 256]
  emb_dim: 512
  k: 5
  decoder_layers: [512, 256, 128, 64]
  dropout: 0.3
  out_channels: 3

train_para:
  batch_size: 64
  accum_iter: 1
  epochs: 100
  lr: 0.001
  num_workers: 0
  weight_decay: 0.001
  scheduler: 
    milestones: [20, 40, 80]
    gamma: 0.5
